/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fairplanner;

import fairplanner.bean.UsermasterBean;
import java.awt.Container;
import java.awt.Toolkit;

/**
 *
 * @author Parvesh
 */
public class MainFrame extends javax.swing.JFrame {

    public static Container container;
    public static UsermasterBean objBean;

    MainFrame(UsermasterBean objBean) {
        initComponents();
        this.objBean = objBean;
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);
        container = getContentPane();
        if (!objBean.getUserType().equalsIgnoreCase("administrator")) {
            mbMainFrame.remove(mnuUserMaintenance);
            mbMainFrame.remove(mnuReports);
        }
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        mbMainFrame = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        menuProfile = new javax.swing.JMenu();
        miProfileAccountDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserAccountDetail = new javax.swing.JMenuItem();
        menuInformationMaintenance = new javax.swing.JMenu();
        miFairTypeMaintenance = new javax.swing.JMenuItem();
        miManageFair = new javax.swing.JMenuItem();
        miManageFairStalls = new javax.swing.JMenuItem();
        menuCompanyFairMaintenance = new javax.swing.JMenu();
        miManageCompanyInformation = new javax.swing.JMenuItem();
        miCompanyFairParticipation = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserAccountReport = new javax.swing.JMenuItem();
        miFairTypeReport = new javax.swing.JMenuItem();
        miCompanyInformationReport = new javax.swing.JMenuItem();
        miFairInformationReport = new javax.swing.JMenuItem();
        miFairStallReport = new javax.swing.JMenuItem();
        miCompanyFairParticipationReport = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        jMenu13.setText("File");
        jMenuBar6.add(jMenu13);

        jMenu14.setText("Edit");
        jMenuBar6.add(jMenu14);

        jMenu15.setText("File");
        jMenuBar7.add(jMenu15);

        jMenu16.setText("Edit");
        jMenuBar7.add(jMenu16);

        jMenu18.setText("jMenu18");

        jMenu22.setText("jMenu22");

        jMenu23.setText("jMenu23");

        jMenu24.setText("jMenu24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        menuFile.add(miLogout);

        mbMainFrame.add(menuFile);

        menuProfile.setText("Profile");

        miProfileAccountDetail.setText("Profile Account Detail");
        miProfileAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileAccountDetailActionPerformed(evt);
            }
        });
        menuProfile.add(miProfileAccountDetail);

        mbMainFrame.add(menuProfile);

        mnuUserMaintenance.setText("User Maintenance");

        miUserAccountDetail.setText("User Account Detail");
        miUserAccountDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserAccountDetail);

        mbMainFrame.add(mnuUserMaintenance);

        menuInformationMaintenance.setText("Information Maintenance");

        miFairTypeMaintenance.setText("Fair Type Maintenance");
        miFairTypeMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFairTypeMaintenanceActionPerformed(evt);
            }
        });
        menuInformationMaintenance.add(miFairTypeMaintenance);

        miManageFair.setText("Manage Fair");
        miManageFair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageFairActionPerformed(evt);
            }
        });
        menuInformationMaintenance.add(miManageFair);

        miManageFairStalls.setText("Manage Fair Stalls");
        miManageFairStalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageFairStallsActionPerformed(evt);
            }
        });
        menuInformationMaintenance.add(miManageFairStalls);

        mbMainFrame.add(menuInformationMaintenance);

        menuCompanyFairMaintenance.setText("Company Fair Maintenance");

        miManageCompanyInformation.setText("Manage Company Information");
        miManageCompanyInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageCompanyInformationActionPerformed(evt);
            }
        });
        menuCompanyFairMaintenance.add(miManageCompanyInformation);

        miCompanyFairParticipation.setText("Company Fair Participation");
        miCompanyFairParticipation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompanyFairParticipationActionPerformed(evt);
            }
        });
        menuCompanyFairMaintenance.add(miCompanyFairParticipation);

        mbMainFrame.add(menuCompanyFairMaintenance);

        mnuReports.setText("Reports");

        miUserAccountReport.setText("User Account Report");
        miUserAccountReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserAccountReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserAccountReport);

        miFairTypeReport.setText("Fair Type Report");
        miFairTypeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFairTypeReportActionPerformed(evt);
            }
        });
        mnuReports.add(miFairTypeReport);

        miCompanyInformationReport.setText("Company Information Report");
        miCompanyInformationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompanyInformationReportActionPerformed(evt);
            }
        });
        mnuReports.add(miCompanyInformationReport);

        miFairInformationReport.setText("Fair Information Report");
        miFairInformationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFairInformationReportActionPerformed(evt);
            }
        });
        mnuReports.add(miFairInformationReport);

        miFairStallReport.setText("Fair Stall Report");
        miFairStallReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFairStallReportActionPerformed(evt);
            }
        });
        mnuReports.add(miFairStallReport);

        miCompanyFairParticipationReport.setText("Company Fair Participation Report");
        miCompanyFairParticipationReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCompanyFairParticipationReportActionPerformed(evt);
            }
        });
        mnuReports.add(miCompanyFairParticipationReport);

        mbMainFrame.add(mnuReports);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void miProfileAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileAccountDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        ProfileDetail obj = new ProfileDetail();
        obj.setBounds(100, 30, 562, 655);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miProfileAccountDetailActionPerformed

    private void miUserAccountDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        UserDetail obj = new UserDetail();
        obj.setBounds(100, 100, 800, 800);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miUserAccountDetailActionPerformed

    private void miFairTypeMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFairTypeMaintenanceActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        ManageFairType obj = new ManageFairType();
        obj.setBounds(100, 30, 562, 800);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miFairTypeMaintenanceActionPerformed

    private void miManageFairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageFairActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        ManageFair obj = new ManageFair();
        obj.setBounds(100, 100, 700, 800);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miManageFairActionPerformed

    private void miManageFairStallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageFairStallsActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        ManageFairStalls obj = new ManageFairStalls();
        obj.setBounds(100, 30, 800, 800);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miManageFairStallsActionPerformed

    private void miManageCompanyInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageCompanyInformationActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        ManageCompany obj = new ManageCompany();
        obj.setBounds(100, 30, 800, 655);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miManageCompanyInformationActionPerformed

    private void miCompanyFairParticipationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompanyFairParticipationActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setVisible(false);
        CompanyFairParticipation obj = new CompanyFairParticipation();
        obj.setBounds(100, 30, 800, 800);
        container.add(obj);
        container.setVisible(true);
    }//GEN-LAST:event_miCompanyFairParticipationActionPerformed

    private void miUserAccountReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserAccountReportActionPerformed
        // TODO add your handling code here:
        new UserReport().setVisible(true);

    }//GEN-LAST:event_miUserAccountReportActionPerformed

    private void miFairTypeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFairTypeReportActionPerformed
        // TODO add your handling code here:
        new FairTypeReport().setVisible(true);
    }//GEN-LAST:event_miFairTypeReportActionPerformed

    private void miCompanyInformationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompanyInformationReportActionPerformed
        // TODO add your handling code here:
        new CompanyInformationReport().setVisible(true);

    }//GEN-LAST:event_miCompanyInformationReportActionPerformed

    private void miFairInformationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFairInformationReportActionPerformed
        // TODO add your handling code here:
        new FairInformationReport().setVisible(true);

    }//GEN-LAST:event_miFairInformationReportActionPerformed

    private void miFairStallReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFairStallReportActionPerformed
        // TODO add your handling code here:
        new FairStallsReport().setVisible(true);
    }//GEN-LAST:event_miFairStallReportActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFileActionPerformed

    private void miCompanyFairParticipationReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCompanyFairParticipationReportActionPerformed
        // TODO add your handling code here:
        new CompanyFairParticipationReport().setVisible(true);
    }//GEN-LAST:event_miCompanyFairParticipationReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenu menuCompanyFairMaintenance;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuInformationMaintenance;
    private javax.swing.JMenu menuProfile;
    private javax.swing.JMenuItem miCompanyFairParticipation;
    private javax.swing.JMenuItem miCompanyFairParticipationReport;
    private javax.swing.JMenuItem miCompanyInformationReport;
    private javax.swing.JMenuItem miFairInformationReport;
    private javax.swing.JMenuItem miFairStallReport;
    private javax.swing.JMenuItem miFairTypeMaintenance;
    private javax.swing.JMenuItem miFairTypeReport;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miManageCompanyInformation;
    private javax.swing.JMenuItem miManageFair;
    private javax.swing.JMenuItem miManageFairStalls;
    private javax.swing.JMenuItem miProfileAccountDetail;
    private javax.swing.JMenuItem miUserAccountDetail;
    private javax.swing.JMenuItem miUserAccountReport;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables
}
